# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cv_show.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 700)
        MainWindow.setMaximumSize(QtCore.QSize(1600, 1600))
        MainWindow.setFocusPolicy(QtCore.Qt.WheelFocus)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox_2.setStyleSheet("background-color:transparent;")
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout.addWidget(self.doubleSpinBox_2, 2, 10, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(81, 18))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setStyleSheet("background-color:transparent;")
        self.label_3.setObjectName("label_3")
        self.step_show_label = QtWidgets.QLabel(self.centralwidget)
        self.step_show_label.setMinimumSize(QtCore.QSize(81, 18))
        self.step_show_label.setMaximumSize(QtCore.QSize(16777215, 40))
        self.step_show_label.setStyleSheet("background-color:transparent;")
        self.step_show_label.setObjectName("step_show_label")
        self.gridLayout.addWidget(self.label_3, 2, 7, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.horizontalSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.horizontalSlider.setStyleSheet("background-color:transparent;")
        self.horizontalSlider.setMaximum(99)
        self.horizontalSlider.setPageStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 2, 0, 1, 7)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setStyleSheet("background-color:transparent;")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setStyleSheet("background-color:transparent;")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setStyleSheet("background-color:transparent;")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setStyleSheet("background-color:transparent;")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setStyleSheet("background-color:transparent;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(81, 18))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setStyleSheet("background-color:transparent;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 12, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.doubleSpinBox.setStyleSheet("background-color:transparent;")
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout.addWidget(self.doubleSpinBox, 2, 13, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 7, 1, 7)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setStyleSheet("background-color:transparent;")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 8, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMinimumSize(QtCore.QSize(100, 18))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_6.setStyleSheet("background-color:transparent;")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 6, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
        self.verticalSlider.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.verticalSlider.setStyleSheet("background-color:transparent;")
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.verticalSlider, 3, 14, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(120, 28))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 7)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMinimumSize(QtCore.QSize(120, 18))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_7.setStyleSheet("background-color:transparent;")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMinimumSize(QtCore.QSize(100, 18))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setStyleSheet("background-color:transparent;")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 13, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setMinimumSize(QtCore.QSize(0, 60))
        self.lcdNumber.setStyleSheet("background-color:transparent;")
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 1, 3, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setMinimumSize(QtCore.QSize(0, 60))
        self.lcdNumber_2.setStyleSheet("background-color:transparent;")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 1, 10, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setMinimumSize(QtCore.QSize(0, 150))
        self.label_11.setStyleSheet("background:rgb(79, 79, 79)")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 15)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("border-radius:10px;background:rgb(79, 79, 79)")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 15)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 37))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.action_1 = QtWidgets.QAction(MainWindow)
        self.action_1.setObjectName("action_1")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        #手动添加4个按钮，用作指示线
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton2.setAutoFillBackground(False)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton3.setAutoFillBackground(False)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton4.setAutoFillBackground(False)
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton5.setAutoFillBackground(False)
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton1.setStyleSheet("border:2px solid rgb(255,0,0)")
        self.pushButton2.setStyleSheet("border:2px solid rgb(255,0,0)")
        self.pushButton3.setStyleSheet("border:2px solid rgb(255,0,0)")
        self.pushButton4.setStyleSheet("border:2px solid rgb(255,0,0)")
        self.pushButton5.setStyleSheet("border:2px solid rgb(0,255,0)")
        self.pushButton1.setEnabled(False)
        self.pushButton2.setEnabled(False)
        self.pushButton3.setEnabled(False)
        self.pushButton4.setEnabled(False)
        self.pushButton5.setEnabled(False)
        self.pushButton1.hide()
        self.pushButton2.hide()
        self.pushButton3.hide()
        self.pushButton4.hide()
        self.pushButton5.hide()
        #添加按钮填满中间空隙
        self.pushButton_l = QtWidgets.QLabel(self.centralwidget)
        self.pushButton_l.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_l.setAutoFillBackground(False)
        self.pushButton_l.setObjectName("pushButton_l")
        self.pushButton_l.setStyleSheet("background:rgb(79, 79, 79)")
        self.pushButton_l.raise_()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "宽度设置："))
        self.label_4.setText(_translate("MainWindow", "高度设置："))
        self.label_6.setText(_translate("MainWindow", "帧率(1):"))
        self.label_5.setText(_translate("MainWindow", "正面相机"))
        self.label_7.setText(_translate("MainWindow", "侧面相机"))
        self.label_8.setText(_translate("MainWindow", "帧率(1):"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "杰克缝纫机定位仪"))
        self.action_1.setText(_translate("MainWindow", "打开相机1"))
        self.action_2.setText(_translate("MainWindow", "打开相机2"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

